import React from 'react'
import { useParams } from 'react-router-dom';
import Navbar from '../Navbar';
import Footer from '../Footer';
import { BsArrowLeftSquareFill } from "react-icons/bs";
import { FiUserCheck } from "react-icons/fi";
import { MdMarkEmailRead } from "react-icons/md";
import './index.css'

const blogData = [
  {
    id: 1,
    title: 'Journey to The Land of the One Horned Rhino -  Kaziranga',
    description1: 'Home to the one thirds of the One Horned Rhino, this is a world heritage site. It also boasts the highest density for the tigers. The thrill of sigthing a tiger in the tall grasses makes one sit on their edge of their vehicle seats. It is also home for large breeding populations of elephants, water buffalos and swamp deer. With all the above species found, Kaziranga is popularly known as The Home For The BIG Five. ',
    imageUrl1: '/blogs/blog-1-1.png',
    description2:"Kaziranga has been identified by Birdlife International as an Important Bird Area. It is home to a variety of migratory birds, water birds, predators, scavengers, and game birds. Birds such as the lesser white-fronted goose, ferruginous duck, Baer's pochard duck and lesser adjutant, greater adjutant, black-necked stork, and Asian openbill stork migrate from Central Asia to the park during winter. Riverine birds include theBlyth's kingfisher, white-bellied heron, Dalmatian pelican, spot-billed pelican, Nordmann's greenshank, and black-bellied tern. Birds of prey include the rare eastern imperial, greater spotted, white-tailed, Pallas's fish eagle,grey-headed fish eagle, and the lesser kestrel. The most endangered Bengal Florican is only found in these jungles.",
    imageUrl2:'/blogs/blog-1-2.jpg',
    description3:'The nearest Airport is Guwahati. There are connecting flights to Guwahati from most of the metros in India. From Guwahati, one needs to drive down to Kaziranga. Guwahati also boasts a very important and a big railway station. For people who love train travel, they too can reach here before heading to Kaziranga. The drive is through one of the first International Highway. This road goes all the way to Burma. They are also extending this road to Thailand.The drive takes about five hours bit it is never boring as the green fields bordering the highway with the farmers working is a treat to ones eyes. Rice is the main crop of this belt.Different varieties of rice are grown here.The increase of tourists have improved the food quality and the places to eat on this highway.There are a plenty of Dhabas ( local food joints) which serve mostly north indian cuisine.Freshly made rotis are a specialty here. They are generally made on the road side and the way they flip it in mid air is something which needs a lot of practice.',
    imageUrl3:'/blogs/blog-1-3.png',
    description4:'There are a lot of festivals being celebrated in this part of the country. The local art and traditions are very well maintained here. One such example is , all the villages have a competition of building a structure of an animal with straw. They call this Bihu Garh. Last year it was this huge bird which won the competition. Off-course the wings have had their toll because of the strong winds.',
    imageUrl4:'/blogs/blog-1-4.png',
    description5:"Enroute at a place called Jagirudh, Asia's largest dry fish market is found. A plenty of paper mills, which use bamboo to make paper line up on both sides of this highway. The mills have a lot of lights and from far they look like small towns. When the driver was questioned , why so many lights are being used for such small establishments, he replied that, a lot of elephants are attracted to these factories as they love the tender bamboo shoots. In the dark they come to raid the place and there have been several occasions where there have been human animal conflict. And during these occasions , mostly a human losses his/her life and so does the animal.",
    imageUrl5:'/blogs/blog-1-5.png',
    description6:'The morning starts off with an elephant ride. Almost ten elephants with their guests on top of them start marching through the tall grass of the forests. Though Indian nationals are permitted to do elephant safaris in all zones, the foreign nationals are allowed only at the Central zone. The elephants carrying the guests go close to the rhinos and their calves which are munching on the succulent grass. On a lucky day, one can sight the exclusive tigers trying to run away from these elephants. Winters and early summers are the best time to see the birds on the grass lands.',
    imageUrl6:'/blogs/blog-1-6.png',
    description7:"Coaching the Rhinos have been a major threat and is leading to the species extinction. The largeness of the park and the easy access from the neighboring countries makes this very easy. The horns of the Rhinos fetch a very high price in the International market. People beleive that the horns have many medicinal values, which is not right.To ensure that this Unesco Heritage site lives for ever, we have to stop buying any product made of animal parts. Please understand, when the buying Stops, the Killing stops!!"
  },
  {
      id: 2,
      title: 'INTO THE SMALL WORLD - Agumbe',
      description1: 'The journey takes about 6 and 1/2 hours to reach the destination, but the drive is definitely an enjoyable one. We started early morning at 5.30 AM and took a left turn at Nelamangala towards Hassan. The four lane highway had very less traffic at that time. But one needs to watch out for the small speed breakers which are laid on the highway, either sides of the small town entrances.',
      imageUrl1: '/blogs/blog-2-1.jpg',
      description2:"They could have built an over bridge like the ones in Tamil Nadu, Gujarat. With very less markings and no sign boards makes these speed breakers highly dangerous. The truck traffic on this road is another thing one needs to exercise caution.",
      imageUrl2:'/blogs/blog-2-2.png',
      description3:"Hassan to Chikmagalur and then through the winding hills of the western ghats, we reached at our destination,Agumbe at 12 noon. We were instructed to go to Malya’s shop and ask for the directions for the Agumbe Rainforests Research Station ( ARRS ). The Malaya’s shop isn’t quite big, but one can buy all the required essentials during their stay at Agumbe and it seems to be a known landmark of the town.The place has a common dinning area and one has to self serve food from the kitchen. Food is mainly veg, but since we requested for non-veg, we had chicken being made one night for dinner and egg for breakfast.",
      imageUrl3:'/blogs/blog-2-3.jpg',
      description4:"I’m taking a little detour here. Me being so much used to shoot mammals from jeep , i have never looked below at the ground. It would always be at my eye level for land mammals or on trees for the leopards, birds and the monkeys. This being the first time, i was doing a serious macro photography trip, my head was always bend down. There are two reasons to this. One, the subjects are really small and they are hidden in the grass. Second, the terrain is not a walk on a flower bed. The vines, leaf litter, fallen and falling trees, gushing streams, hidden pits, and finally the snakes, get every reflex of one working. But still, i was figuring our why Catherine (our spotter, about whom i have a separate para at the end) was so excited.The reply was, the leaf insect. This insect is very difficult to sight because of its camouflage.Another major challenge while doing macro photography is to get the subject in open. Many think that it is easy to handle all the subjects, get them to open, set up shots and shoot. I know, some people do this. But at ARRS, this is a clear ‘NO’. So we had to wait for the insect to come to an open twig and then get our shot/s. The lenses were getting foggy and off course we were drenched to the bone. This being the routine, i strongly advice people who visit this place for photography to take two helpers to carry external flash lights, tripod, cameras and enough dry towels to keep wiping the equipment.Twenty minutes into the rain forests, i was completely disoriented. This was the first time in my life i felt, how small a creation humans are!!! Though i was struggling to keep up pace with our guides and mentors , Vipul and Catherine, there was always a fear lingering of what i would do if i lost my path. The fear gives birth to strength. This was an out of the world experience for me. The strength was telling me to keep up and just concentrate on what i was here to do. I could feel the warm blood dripping from my hand, inside my rain coat. I was constantly wiping the blood from my neck from a fresh leech bite, but still, i was on my way to one of the most beautiful places on earth.",
      imageUrl4:'/blogs/blog-2-4.jpg',
      description5:"The roar of the water fall, was the best sound i could hear after a hour and a half hour walk into the unknown. The first sight of the water fall was breathtaking. The force of the water flowing was to much. I need to accept here that i’m not a great swimmer. And even i was, i wasn’t going to take a chance in this place full of rocks and rapids. So , slowly taking one step at a time, i positioned myself to get the best view of the fall.This is the first time i felt, i could have brought two helpers and some more artificial lights to get a magical picture of the scene. But having come so far, we had to get the best out of the situation. So with a slow shutter speed and a filter, we could manage a nice silky flowing water with boulders and ferns growing on them. The trees were so huge that even a fish eye would not have covered the entire scene.",
      imageUrl5:'/blogs/blog-2-5.jpg',
      description6:"The walk back wasn’t that bad cos we were used to the terrain. But the fallen trees made us to take a longer detour and reach our camp. The rains had made the little streams swell and the ferns inside the water seem to be welcoming us for a nice breakfast. The ‘Dosa’ ( sort of a pan cake made out of batter ) and scrambled eggs satisfied our hunters’ appetite. While on breakfast, we received a news that a GREEN MORPH PIT VIPER has been sighted inside the camp and was on a very good perch. We ran with our equipments and found the snake relaxing on a ‘dream perch ‘like how the photographers’ call it.The pit vipers are extremely patient when it comes to holding on a perch for longer duration of time. People have seen them hanging down i their ambush position for seven days in a row. They wait patiently for the prey to come below the branch and in a flash lunge to grab them. They strike so fast, that they put the fastest cameras to shame. We knew we had time, so i tried a lot of angular lighting and managed some good shots.",
      imageUrl6:'/blogs/blog-2-6.jpg',
      description7:"The long walk to the falls, followed by a heavy breakfast and then some satisfying shots of the pit viper turned out to be a lullaby for my sleep. I got up well past 2PM, just for another round of food. Lunch was simple, as we had some work to catch up with. The green vine we spotted on day one was completely on the open today. This provide us with some good opportunities to try out our lighting skills and wide angle shots. The minute any part of the plant where the snake is perched is touched, they start to move. This was the slightest mistake i did when i had to go close with my wide angle. Though i managed a couple of wide angle shots, if i would have been careful, i could have managed them better."
    },
    {
      id: 3,
      title: 'The Tiger Capital of the World - Bandhavgarh',
      description1: "Three years before when i started this company of wildlife tours, Bandhavgarh was an unknown name to me. I always had a feeling that all parks of Central India were very similar, dry and barren. It was Mr. MN Jayakumar , who pushed me to do a trip to this place. Using his pictures and what ever he told me about this place, i floated a tour. As he was the mentor, i had no difficulty in filling up the tour. The journey was on and i too was a guest!!! One fast way to reach Bandhavgarh is to fly to Jabalpur and take a cab. Jabalpur is connected only from Delhi and Mumbai. I chose to fly to Mumbai as we were flying from Bangalore. It was June and i was told that it would be extremely hot at Bandhavgarh. Going from a place like Bangalore which doesn’t get that hot, i was a bit cautious, but did want to think too much.",
      imageUrl1: '/blogs/blog-3-1.jpg',
      description2:"The early morning flight from Bangalore to Mumbai takes less than two hours. Then there is this waiting period at Mumbai as the flight to Jabalpur is at 2.30PM. The sandwiches and milkshakes gave us company at Mumbai airport. I did not feel the heat and this was because i was in an AC atmosphere inside the airport. The flight to Jabalpur is a small aircraft with 30 odd seats. With a lot of difficulty i pushed my camera bag into the over head luggage compartment.The flight landed at 4.30 PM, and the minute i stepped out, i knew what it would be for the next five days.It was like someone pouring a bucket of very hot water on my face. Phew, it was hot, very hot!! I ran to my cab and sat too realise that it was like an oven.We did not enter the city but took a short cut to the highway. The place did look dry and barren as i expected. But as we were nearing Bandhavgarh, i could sense of change happening in me. I did not know why then!! Something kept on saying that, i was making mistake about this place. Finally we reached pour resort.",
      imageUrl2:'/blogs/blog-3-2.jpg',
      description3:"Aryanak, the resort where we had booked, is owned by Mr. Harshvardhan, who himself is a great nature lover and is very popular at Bandhavgarh. He became popular because he actually jumped from his vehicle to save a tourist who was being attacked by a tiger. How did he muster courage to do this, still remains a question. He is a very strong man with a heart of a kid. The resort is know for its hospitality and customer service.Evening was pleasant, and after dinner we retired for the night. The distant roar of the tiger and the me trying to get a glimpse of it was my only dream that night. Early morning at 5AM, we were served tea and our jeeps were ready. Ravi, who owns the safari jeeps was ready to welcome us with a smile very few in this world have.",
      imageUrl3:'/blogs/blog-3-3.jpg',
      description4:"For a minute, i thought it was a small fox, but the stripes behind the bushes gave it up. It was a cub of this huge male who was quenching his thirst. Half hour into the jungle, we had a family of tigers in from of us. Now i knew, why Bandhavgarh is referred as the The tiger capital of the world. My entire perception changed. It has changed so much that this is my second most favourite park after Corbett in India.There is a central part of the park which is a common place for Tala and Magadi zones. Here the villagers set up stores and sell hot tea, cool drinks, samosas, and maggie. We went there for a much needed rest.",
      imageUrl4:'/blogs/blog-3-4.jpg',
      description5:"The safari continued and we stared to explore the other parts of tiger park. Tala zone is very picturesque. It starts with a grass land, and then the terrain gets a little undulating, but then it ends with a grass land. It has the mighty mountains on one side of it. Magadi is a little narrow as it starts but opens up beautifully to the meadows and then climbs up to a hillock. Khitalui is a difficult terrain, but the famous Male tigers have found this zone a safe haven.",
      imageUrl5:'/blogs/blog-3-5.jpg',
      description6:"Every tiger has been given a name here!!! The area in which they operate is their prefix unlike the filmy names one gets to hear at Tadoba. Bamera male, Magadi female, Rahbera male etc. The new entrants have not yet got re-christened. Funny isn’t it, and thats what the tigress seem to be saying!!! The morning safari ends at 10.30 and it takes another half hour to reach the resort. And the reason is not because the resort is far, it because of the local delicacy we have on the way. The chenna ( chin pea ) with onion and masala, followed by the sweet jamun in rabdi ( a sweet made of flour, sugar syrup, dipped in sweet cream of milk ). This is the best food one can ever have after sighting the King of the jungle.",
      imageUrl6:"/blogs/blog-3-6.jpg",
      description7:"Getting to the spot early had its advantages. The cubs were just about finishing the kill and heading towards the mountains to rest. We managed some very good shots of them and finally retired at the resort. It was party time then.Sadly every journey comes to an end. But the journeys i have been taking to the tiger capital would always be edged in my memory for ever.",
    },
    {
      id: 4,
      title: 'CORBETT TIGER RESERVE - The Land of Roar and Trumpet',
      description1: 'Away from the crowd packed like sardines, nestling in the foot hills of the mighty Himalayas, lies this beautiful peace of earth called Corbett. River Ramganga quietly flows cutting this valley into two. The upper regions boast of thick vegetation while the lower grass lands sway gently with the cool northerly winds. The birds started their dawn chorus as we drove along the banks of Ramganga, when we heard a throaty bark somewhere inside the forest.',
      imageUrl1: '/blogs/blog-4-1.jpg',
      description2:"Tourists are allowed in selective areas of the park. There are close to 70,000 visitors every year and the crowd has been on the increase. Corbett has got more than 488 species of ‘fauna’ and a variety of plants. This makes it one of the best parks in the world. After a two and half hour flight from Bangalore to Delhi, i descended on a cold winter evening to board the Rhaniket express from the old Delhi railway station. The drive to the station took another two hours. Buzzing with passengers, Old Delhi railway stations is one of the busiest places on earth. With the help of a porter i had my heavy equipments safely kept under my seat.Tucked inside my blanket, i woke up when i heard the train slowly saying, ‘when she can do it, i can do it, when she can do it, i can do it’ as she came to a halt at a station called Ramnagar.Ramnagar is a small little town, located 65 kilometers from Nanital and it is the district head quarters. It is the gateway to Corbett. The town now is filled with resorts which can cater to any segment of people. Garjiya Devi and Sita Bani temples located nearby also attract many visitors to this place.",
      imageUrl2:'/blogs/blog-4-2.jpg',
      description3:"That morning the most welcoming sight i had was of my driver cum guide and the Gypsy (the jeep) which would be with me for the next seven days. I would like to mention about Irshad, my driver, whom i would rather refer as the Best Naturalist i have ever come across. His knowledge about the jungles and its dwellers is first among equals. His only aim is to learn new things every day, this makes him very attentive to calls and close to nature.After a quick exchange of greetings, i was in my Gypsy on the way to Dhikala, the heart of the reserve. We had to enter through Dhangadi gate. The Dhikala forest rest house is located 30kms from the gate. The one to one and half drive through from the gate would make anyone sit on the edge of their seat. As Irshad was driving slowly through the thick Sal forests (which covers 80% of Corbett), i was checking up my camera settings. Now i was in the jungle!!! The first halt is at ‘Crocodile Point’. The view from here is breathtaking.",
      imageUrl3:'/blogs/blog-4-3.jpg',
      description4:"Stooping at the river side, driving through the dense jungle, hearing for alarm calls, anxiously waiting for the cat to appear, we return to the rest house as the orange globe descends the western horizon. A little depressed for not sighting the tiger, i still keep looking at both the sides. “Sir, tomorrow, we would take Sudhir. He is the luckiest person for me”, says Irshad. “He is a very good tracker too”..Then comes the glimmer of hope, cos when you have two of the best i’m sure no cat can escape. The place becomes dark pretty fast and dinner is served at 7.30 onwards to 9.00PM. I have an early dinner and hit the sack. Rajesh my attender is at my door sharp at 5.30AM with a hot cup of tea. The hot water from the geyser raises my hopes even more.Into my warm clothes i walk upto to my Gypsy to be greeted by both the masters of the jungle. Off we were at a famous jungle track where the big cat sighting is comparatively easy. Flanked by tall grass on both the sides, i stood up to get a clear view. The morning mist and the cool breeze makes one feel that you are in heaven. The details of Corbett which Sudhir was giving to me suddenly came to a grinding halt as Irshad jamed the brakes. “Alarm call”, yes it the cheetals’ (spotted deers) who were on high alert. “Sudhir, it is on the ‘thand’ (hindi word for cold) road, go go go”, i whisper as my blood streams raise northwards. We enter the road and we already have company. There were two more jeeps with guests waiting anxiously. The alarm calls grow in sound, and the forest floor starts to reverberate with them. “Sir, don’t take your eyes of your camera, she will come any minute” , says Sudhir. ‘come , come, come’ i keep murmuring as my eyes are stuck to the view finder. Then she arrives. The shutters go like machine guns, but she is seldom bothered, it is her land and she is the undisputed queen. Like a phantom she vanishes into the tall grass and we are all left speechless. I knew i had got my dream shot, ‘The Tigress in the Mist’",
      imageUrl4:'/blogs/blog-4-4.jpg',
      description5:"The show lasted for twenty minutes and then the cubs disappeared behind the bushes again. We waited for some more time,before we called it a day. The next day we got a glimpse of a cub and the remaining part of the day, it was the jungle itself which made me feel enthralled. Listening to the songs of the birds i returned to my guest house to pack my bags for my journey back home.As my aircraft lifted up from Delhi i closed my eyes to see the landscape refreshing as cucumber pads for the eyes and the heavens were feeling-indeed they were -that much closer!! Corbett National Park..’The Mother of Wild India’",
      imageUrl5:'/blogs/blog-4-5.jpg',
      description6:"I thanked all up heavens as we returned to our rest house. The afternoon safari started with a lot of hopes. Every gypsy is in and around the Mota Sal (the biggest Sal tree which got burnt by a lightning years back). We thought we should try the other part of the jungle. We drive alongside the banks of Ramganga. This part of the jungle seem to be devoid of any big cat movement, but it was real action time with the birds. The Pied Kingfisher hobbing over the river, swooping elegantly to pick up the fish, the lesser fish eagle taking off from a high perch in search of its prey, the small blue Kingfisher sitting on the rocks,patiently waiting for the fish to show up was a treat to ones’ eyes.",
      imageUrl6:'/blogs/blog-4-6.jpg'
    },
    {
      id: 5,
      title: 'Laikipia, Kenya’s Wild Dog’s Country',
      description1: 'I hit the panic button, when my scheduled flight from Masai Mara did not land at 11AM. This was because, my connecting flight was at 13.00 hours from Nairobi to Nanyuki.',
      imageUrl1: '/blogs/blog-5-1.png',
      description2:"The name Laikipia has its origins with the Laikipiak Maasai, who once moved through this area.They were defeated and dispersed by the ancestors of the modern Kenyan Maasai in a series of major battles during the 19th century. Today Laikipia is predominantly the land of the Samburu and some Western tribes belonging to the collective The long conversation with Peter made him understand my interest in wildlife. This made him call for a 4*4 to pick me up mid way to show the most coveted painted Wild Dogs of Laikipia. The sight of the 4* 4 is the most welcoming thing for any wildlife lover’s eyes. Ambrose, the seven footer was introduced by Peter. His hand shake really shook me from the bottom. In hardly five minutes, me and Ambrose were off into the jungle of Laikipia country.Ambrose, hails from Samburu and he has been working with Sosian lodge for more than ten years.For the last eight years he has been trickling the last remaining Wild Dogs of this region. He carries the antenna which one uses to track the collared dogs. Out of the 18 dogs remaining, 6 are collared. They are the old and matured ones who lead the pack.",
      imageUrl2:'/blogs/blog-5-2.png',
      description3:"We had many twists and turns and Ambrose on the bonnet every 10 minutes, but no sign of the wild dogs. Up he drove the hill to get to the vantage point. Once again he was on top of the vehicle, when we heard a faint beep. It was like hearing one’s own heart beat after a 100 mts run. He drive exactly to the place where we heard the beep, and there were the Wild Dogs by the river.This was the first time in my life i had sighted them. Though they were down and far, i could feel my hands shaking. Quickly Ambrose turned the vehicle and waited along side a narrow path and said, “ get down and crawl, don’t worry, they wouldn’t do anything”. With all the excitement i jumped down with my 200-400 long lens. The mistake i would never forget. The dogs were so inquisitive about this Indian lying down, that they came so close to sniff my cap.The dogs were hungry and they were in the hunting mood. They possess an excellent communication skill. Running into the bushes, they managed to bring down a Dik Dik ( the smallest antelope of Africa) and a Impala. We could hear the cries, but both the kills were finished before we could enter the bush. Leaving the dogs behind, we headed for the lodge.",
      imageUrl3:'/blogs/blog-5-3.jpg',
      description4:"Next morning we were up early scouting for the Reticulated Giraffes and the Gravy zebras. These beautiful species are found in plenty at Laikipia. There are two rivers which flow across Laikipia.Eves Niro and Evaso Narok, both originate from Abadas and cut across Laikipia. They join here and flow through the Samburu National park. As it is cold out here, the crocs are found 15 to 20 kms upstream towards Samburu.The elephants of Laikipia are a little more suspicious than the ones at Mara or Amboseli. I think this is because they live in a bushy terrain and they are surprised when they come across other species. Whereas at Amboseli, the Savannah is very open and plain and there are very few occasions one can surprise these gentle giants.",
      imageUrl4:'/blogs/blog-5-3.jpg',
      description5:"Laikipia is very rich in bird life too. Raptors like the Chanting Goshak, Augo Buzzard are commoners. The Vulturine Guineafowls are endemic to Laikipia and Samburu areas.They are very colourful birds and called so bcos of their necks. After filling the memory cards of my camera with these amazing species, i headed towards the river to join an young couple for a river side dinner. The setting was truly Hollywood. I had to satisfy their request to click some pics.Ambrose and me then returned to the camp. The cold breeze were making the lanterns outside my room dance. With thoughts of me standing on the Sotinyiro hill, tracking the wild dogs, i retired for the night listening to the distant roar of the King.",
      imageUrl5:'/blogs/blog-5-3.jpg',
      description6:"They are very colourful birds and called so bcos of their necks. After filling the memory cards of my camera with these amazing species, i headed towards the river to join an young couple for a river side dinner. The setting was truly Hollywood. I had to satisfy their request to click some pics.Ambrose and me then returned to the camp. The cold breeze were making the lanterns outside my room dance. With thoughts of me standing on the Sotinyiro hill, tracking the wild dogs, i retired for the night listening to the distant roar of the King.",
      imageUrl6:'/blogs/blog-5-3.jpg'
    },
    {
      id: 6,
      title: 'Magical Masai mara',
      description1: 'The view of the Kenyan coast line from the window is one of the most welcoming sight and a treat to ones eyes.  Masai mara, has always been a dream destination for me to go. From my childhood days, it was this land which made me get very close to wildlife and wilderness. When the opportunity came in 2010, i jumped.',
      imageUrl1: '/blogs/blog-6-1.jpg',
      description2:"One needs to travel to Nairobi and then from there proceed to Masai Mara. Convincing the Kenyan Airline service personal on the excess baggage and hand carry can be dealt only by hard core sales guys. The long serpentine queue to clear the immigration at Mumbai turns any human patient. Then comes the customs. Usually the blood pressure goes up here, but the compulsion to keep shut, gets out the artificial smile on ones face. The easier way is to fly Emirates, have a stop over at Dubai and then land at Nairobi. There are direct flights from Bangalore, Delhi and Mumbai.I’m sure the other major cities around the globe are also well connected by Emirates.",
      imageUrl2:'/blogs/blog-6-2.jpg',
      description3:"After customs clearance, i got some time for a much needed drink. The duty free shop at Mumbai airport sell very good stuff. From chocolates to liquor, this is one stop for all age groups.The two english movies on the flight kept me awake for a while but the food helped me to close my eyes . The six hour flight to Nairobi, seemed to be a long haul as the excitement in me was growing. VISA is on arrival, but for the last two years, the Kenyan Govt is also issuing online VISA.I’m sure the VISA on arrival would stop over the coming years.",
      imageUrl3:'/blogs/blog-6-3.jpg',
      description4:"Lake Nakuru, is a bird watchers paradise on the floor of the rift valley, surrounded by bushes and grassland. Including the greater and lesser flamingos, there are more than 450 species of birds.There are 56 species of mammals, including the white rhinos. The lions at Nakuru seem to have specialised in climbing trees. One gets to see the BIG 5 at lake Nakuru. For me it is the flamingos which drives me back to this place. There are about 550 different plant species including the unique and biggest euphorbia forest in Africa, picturesque landscape and yellow acacia woodlands.The view from the Baboon cliff down the lake is truly a magnificent sight.Lake Nakuru Lodge and Sarova Lion Hill Lodge are two very good places to stay here.",
      imageUrl4:'/blogs/blog-6-4.jpg',
      description5:"The first look of Masai Mara is breath taking. With the over head cover pushed up, i was breathing the fresh air of Masai Mara. The Giraffes and the Zebras are generally the first animals one get show up. Along with them off course the Wildebeests and the Gazelles are also commoners.The greater Maasai Mara – is a continuous landscape approximately the size of 6,000km to that forms the northernmost part of the Serengeti-Mara ecosystem. It is generally defined by the area used by the annual wildebeest migration and includes the Maasai Mara National Reserve,neighboring private and community lands and the adjoining Loita Plains. It has been calculated that 30% of Kenya’s wildlife is in the Greater Mara ecosystem. The land at the reserve is owned by the Kenyan Govt, who in turn have leased/sold to the resorts and lodges.",
      imageUrl5:'/blogs/blog-6-5.jpg',
      description6:"The game drives at the conservancies start very early unlike at the National reserve. This gives excellent opportunities for everyone to watch the wildlife at Sunrise. The game drives extend well into the night. The night life at these places are a must see. The predators who are awake and go for the kill. After the sundowners, we are returning to our camp, when our vehicle broke down.There was no way to pull the vehicle out of the slush. Jackson called for help and we were quickly shifted into another vehicle. The driver, Machio, was very experienced and he knew the subjects very well. That late evening, the behaviour of the lion pride made it clear that they were out to kill.The poor eland which was targeted did not know the strength of the pride. The sub adult male lion which jumped on the antelope received the kick of his life, but the experienced Mama, got the eland down in a snap. Then it was feasting time. The sub adult male who’s ego was hurt was the last one to come and feed on the eland.",
      imageUrl6:'/blogs/blog-6-6.jpg',
      description7:"There are three main river crossing points. We parked at a very strategic position as our drivers expected the huge gathering of Wildebeest would cross exactly where we wanted. The river crossing is a wait and watch game. The thirst and the greener pastures on the other side of the river make these angulates to cross the river. It is for this great show, the entire world gathers at Mara every year. The pressure which builds up on the banks of the river makes the first animal to take the plunge, then it is let loose. The whole scene is so mayhem and chaotic. The rivers are filled with crocs and hippos."
    },
    {
      id: 7,
      title: 'Journey to the Mogul’s Home - Pench National Park',
      description1: 'I always had a thought that Nagpur was only for oranges and water coolers. But a two and half hours journey from Nagpur, you enter where the world famous wolf child,  Mowgli hailed from. Rudyard Kipling made this place world famous with his ‘Jungle Book’  and it continues to be on the world map because of its most beautiful jungle.',
      imageUrl1: '/blogs/blog-7-1.jpg',
      description2:"The forests of Pench, exhibit tremendous diversity in terms of floral elements. The tropical dry deciduous forests boasts more than 1200 species including several endangered and eco-biologically important ones. There are patches of bamboos intermixed with forest and grassland,making this a perfect land for the wild animals.Including the tiger and the leopard which are on the top of the food chain, there are about thirty nine species of mammals found here. The mega mammals are Gaur, Sambhar, Spotted deers,Nilgai, Barking deer, Indian Gazelle, Sloth bear, wild dogs, langurs, rhesus macaques etc.",
      imageUrl2:'/blogs/blog-7-2.jpg',
      description3:"wildlife. May because they do not differentiate as us!! Tourism has increased since BBC released the film “Spy in The jungle” in 2008, a documentary narrated by Sir Davis Attenborough, that has beautifully captured behavior of the Tigers. Walt Disney Production ‘The Jungle Book” animation film was first to introduce Pench to the World.From the luxury to the budget resorts, there are plenty at Pench. This gives everyone an opportunity to explore the jungle without pinching their pockets. My experience in this forests has been very interesting. Monu Dubey is other person who arranges all our trips. He like Ravi of Bandhavgarh, is extremely passionate about wildlife and his love to nature is second to none.",
      imageUrl3:'/blogs/blog-7-3.jpg',
      description4:"When my guest called me late one night, saying that there are no rooms on his name, i got shocked. I spoke to the person at the reception and he claimed that he is the owner of the place and obviously he was very rude over the phone. I had to explain to him about the group travel and the guest was one among our group. Finally he agreed and they spent the night there.Next after noon when we arrived, the rooms wren’t ready and the guests who checked with difficulty came to me and informed that even tea wasn’t provided in the morning. The owner, was around but did not have the courtesy to even welcome us. It hardly took five minutes for me to decide and change the resort. It cost me money but my customers were super delighted.",
      imageUrl4:'/blogs/blog-7-4.jpg',
      description5:"I was using the SONY alpha 99 m2 for the first time and it proved a very worthy one. After sighting this male, we all headed to a water hole which was ruled by a tigress. Her name is ‘Collar Wali’.This is because she was collared by the forest officials to track her territory. Like the ‘ Machli ‘ of Ranthambore, this tigress is very famous in Pench. She has littered the maximum number of times and had produced more than twenty cubs. She with her experience has also brought them up very successfully. During this visit of us, she had very young cubs. As Monu mentioned she was on time!!! She drank a lot of water and settled down in water to cool herself. Her cubs weren’t with her.Probably she might of hidden them in the bushes.",
      imageUrl5:'/blogs/blog-7-5.jpg',
      description6:"I had taken six kids on this trip and they were on top of the world after learning how to take pictures from our Mentor, Mr. Dinesh Kumble and very happy with the number of cat sighting they had. The fun trip sadly had to come to end, as we had to return home!! But Pench, like Bandahvagrh is another extraordinary park and a must visit for any nature lover. This is one reason why we as a company do trip to this park twice a year. Just to see the land where Mowgli lived..",
      imageUrl6:'/blogs/blog-7-6.jpg',
    },
    {
      id: 8,
      title: 'Tadoba - The Land Of Tigers',
      description1: 'It was 50 degrees Celsius. We had covered our faces with a piece of cloth and only our eyes were exposed. Sweating hands couldn’t hold the camera because of the heat. But still we were waiting cos we knew the King would arrive and he did. Panting in this heat the dominant male tiger known as ‘The Wagdoh’ walked slowly towards the Telia lake and immersed himself.',
      imageUrl1: '/blogs/blog-8-1.jpg',
      description2:"TATR or Tadoba Andhari Tiger Reserve lies Chandrapur district of Maharastra in Central India. It is the largest and the oldest national park of Maharastra. Tadoba is a name of the God praised by the forest dwellers and Andhari is the river that meanders through the forest.",
      imageUrl2:'/blogs/blog-8-1.jpg',
      description3:"TATR is very unique that the other forests I have seen cos a road runs across the entire stretch of the jungle and it is a very highly commuted one. Buses ply,villagers use other modes of transport to go to their places, but they peacefully co-exist with the wildlife. The forests are on both the sides of this road. On numerous occasions’ tigers, wild dogs, leopards are sighted on the road and the vehicular movement stops till they get inside the jungle!!",
      imageUrl3:'/blogs/blog-8-1.jpg',
      description4:"As the park lies in Central India, the weather is extreme. Summers are scorching hot and winters are extremely cold. Despite this, wildlife lovers flock this place because one is bound to see a tiger, leopard and other wild animals during summer near the water holes and the famous lakes inside the park.",
      imageUrl4:'/blogs/blog-8-1.jpg',
      description5:"Winter is also a good time for birds. Though TATR does not boasts’ birdlife equal to Corbett and other forests, it has a decent enough species of birds. Birds of prey like the Twany eagles, Cresent Serpent eagles, Shikras, Black shouldered kites are found in abundance. Other small birds like the Kingfishers, Asian Paradise flycatchers, Drongos , Indian Pittas are found near the small ponds and lakes.",
      imageUrl5:'/blogs/blog-8-1.jpg',
      description6:"In the last four years this jungle has been attracting hordes of tourists and wildlife photographers because of the increase in Tiger population. The tigress in TATR have been littering and bringing up their young ones very well. The cubs are fun to watch. Male tigers have very clear and established territories. The pople around TATR and the guides have given names to the tigers like Maya, Gabbbar,Shivaji etc. This sounds a little funny but makes it easy to recognize them. TATR is the Real land of the tigers!!",
      imageUrl6:'/blogs/blog-8-1.jpg'
    },
    {
      id: 9,
      title: 'Birding at The God’s Own Country - Thettekad, Kerala',
      description1: 'An hour and a half journey from Cochin takes you to one of the most desired birding destinations of the Indian subcontinent. The silent town of Thettekad surrounded by the dense forests is home for more than 500 species of birds. Thettekad is also hime for the most famous ‘Salim Ali bird sanctuary’.',
      imageUrl1: '/blogs/blog-9-1.jpg',
      description2:"We arrived at Cochin early morning. Cochin is one of the busiest cities in Kerala. It is s surprise why this is not the capital of the state!! The airport at Cochin is the only ECO friendly airport in India. The way they have maintained this airport is a lesson for many other states in the country. It is a small Airport, but they are extending it as they do have a lot of International flights from here.As we had pre-booked our cab to Thettakad, we had our driver waiting for us outside. Though there are many prepaid taxi booking counters at the airport, it is suggested to have the cab pre booked, when making booking at Thettakad. This would save a lot of time.",
      imageUrl2:'/blogs/blog-9-2.jpg',
      description3:"Without entering the city, we started our journey to our destination. The roads in Kerala aren’t that broad but very well maintained. The drive takes one through lush green fields and huge bunglows. One more highlight about this state is it very continuous. The bigger towns though are spaced , one does not get the feeling of driving through any vacant spaces. This is bcos of the small villages in-between these towns. Also the rivers,streams and hills make the drive very pleasant. The weather is not that friendly as Kerala is on the western coast. It is humid, but the greenery make one forget the humidity. Summers would be hot, so i recommend people to travel to this place during the winter months, from August to end Feb. This is also a very good season for bird watching.",
      imageUrl3:'/blogs/blog-9-3.jpg',
      description4:"After a quick stop over for breakfast, we reached our destination at quarter past 11AM. The early morning flight was making me feel sleepy, but since the program was so tightly packed, we did not have much time to relax. We set up our cameras on the tripods and heard to lunch at 1pm. lunch served at the resort is very simple but very healthy as it is home made. One has to inform while booking whether they are vegetarians or non-vegetarians.",
      imageUrl4:'/blogs/blog-9-4.jpg',
      description5:"I have to mention about the resort. I feel this is more of an extended home than a resort. The place is run by a gentleman called Eldose and his daughter, Ashy, who is a Mechanical engineer, helps him. It is a family run business. Eldose is around his mid fifties, but is fitter than a thirty year old. His experience and knowledge on the birds is outstanding. His love towards nature has made him matin this large property and not converted into a agricultural piece. They do have a rubber plantation along with a small piece of land used for growing paddy, but most of the property merge with the surrounding forests.",
      imageUrl5:'/blogs/blog-9-5.jpg',
      description6:"There are three bird hides and are at different properties near to the place where we stay. All the three have bird baths and attract various species of birds. The bird hides are very well designed and have enough space for 6 people to sit comfortably. The most important thing while setting up hides is to have the bird perched at eye level of the photographer. Secondly, to have a very clear background. Third , and the most important things is to have the hides been with the surroundings. Birds unlike like mammals and are very skittish and fly away even with the slightest sound.",
      imageUrl6:'/blogs/blog-9-6.jpg',
      description7:"AT 6 pm the activity stopped and finally we got out of the hide. As mentioned the schedule at this place is very tight, we had to rush back to the resort. The reason for this was to capture the Molted Owl, which is a daily visitor to the farm. This did surprised me as to why this bird has been visiting the farm almost at the same time to the farm. The answer was right in front of my eyes. The small light outside Eldose’s house made the rats visible to my eyes and this is why the Owl was there. We had to prefocus on the branch where we were told that the Owl might perch. All set, again it was the waiting game. At 7.45PM, the Owl turned up. He sat on the branch just for a few seconds before he swooped on the rat. How many he caught at one shot, how many he gobbled, no one could say as it was pitch dark. The torch light on the branch assisted us to take our shots. There is a strong advice not to use flash light on the animals, i agree to this. But this was shown for two seconds if i’m right. This was the most difficult shot for me. Quite happy about the result and the day, we returned to our room for the much needed dinner and rest.Next day morning, we were up very early as we had to go for the Indian Pitta. This is a resident bird at the farm and does come out for the worms very early in the morning. Again getting the right shutter speed was a challenge in such low light conditions. But with a very high ISO , i did manage to get the shots."
    },

  
];

const BlogDetails = () => {

  const { id } = useParams();
  const card = blogData.find((c) => c.id === parseInt(id));

  if (!card) {
    return <div>Card not found.</div>;
  }

  const handleBack = () => {
    window.history.back();
  }


return (
  <>
  <Navbar/>
    <div className='blog-container'>
        <h1 className='mb-3 mt-3 blog-head'>{card.title}</h1>
        <p className='blog-description'>{card.description1}</p>
        <img src={card.imageUrl1} alt='blog' className='blog-img'/>
        <p className='blog-description'>{card.description2}</p>
        <img src={card.imageUrl2} alt='blog' className='blog-img'/>
        <p className='blog-description'>{card.description3}</p>
        <img src={card.imageUrl3} alt='blog' className='blog-img'/>
        <p className='blog-description'>{card.description4}</p>
        <img src={card.imageUrl4} alt='blog' className='blog-img'/>
        <p className='blog-description'>{card.description5}</p>
        <img src={card.imageUrl5} alt='blog' className='blog-img'/>
        <p className='blog-description'>{card.description6}</p>
        <img src={card.imageUrl6} alt='blog' className='blog-img'/>
        <p className='blog-description'>{card.description7}</p>
        <div className='mt-5 text-center'>
          <h5><FiUserCheck/> By k.chandrashekar</h5>
          <p><MdMarkEmailRead/> ck@travelunbounded.com</p>
        </div>
    </div>
    <div className='text-center mb-3'>
    <BsArrowLeftSquareFill size={30} onClick={handleBack}/>
    </div>
    <Footer/>
    </>
  )
}
export default BlogDetails;
